# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkkeeper', '0006_auto_20151115_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitschedule',
            name='cron',
            field=models.CharField(default='', help_text='* * * * *', max_length=50, verbose_name='Cron-style schedule'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='cron',
            field=models.CharField(default='', help_text='* * * * *', max_length=50, verbose_name='Cron-style schedule'),
        ),
        migrations.AlterField(
            model_name='monit',
            name='worker_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monits', to='parkkeeper.WorkerType'),
        ),
        migrations.AlterField(
            model_name='monitschedule',
            name='count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='monitschedule',
            name='interval',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='monitschedule',
            name='period',
            field=models.IntegerField(editable=False, help_text='in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='worker_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='parkkeeper.WorkerType'),
        ),
        migrations.AlterField(
            model_name='workertype',
            name='port',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='interval',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='period',
            field=models.IntegerField(editable=False, help_text='in seconds', null=True),
        ),
    ]
